FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
ARG NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
